os: Visual Studio 2015

version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
  - develop
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: dotnet --info
- ps: dotnet restore
- ps: dotnet build src\DotNetCoreDocs
- ps: dotnet restore test\DotNetCoreDocsTests
- ps: dotnet test .\test\DotNetCoreDocsTests -c Release
- ps: dotnet pack .\src\DotNetCoreDocs -c Release -o .\artifacts
test: off  
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  name: production
  api_key:
    secure: /fsEOgG4EdtNd6DPmko9h3NxQwx1IGDcFreGTKd2KA56U2KEkpX/L/pCGpCIEf2s
  on:
    branch: master
    appveyor_repo_tag: true